package edu.jhu.cvrg.dbapi.factory.hibernate;

// Generated Dec 7, 2013 2:31:41 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Coordinate generated by hbm2java
 */
@Entity
@Table(name = "coordinate", schema = "public")
public class Coordinate implements java.io.Serializable {

	private Long coordinateId;
	private Double xCoordinate;
	private Double yCoordinate;
	private Set<AnnotationInfo> annotationInfo = new HashSet<AnnotationInfo>(0);

	public Coordinate() {
	}

	public Coordinate(Long coordinateid) {
		this.coordinateId = coordinateid;
	}

	public Coordinate(Long coordinateid, Double xcoordinate, Double ycoordinate) {
		this.coordinateId = coordinateid;
		this.xCoordinate = xcoordinate;
		this.yCoordinate = ycoordinate;
	}
	
	public Coordinate(Long coordinateid, Double xcoordinate,
			Double ycoordinate,
			Set<AnnotationInfo> annotationInfo) {
		this.coordinateId = coordinateid;
		this.xCoordinate = xcoordinate;
		this.yCoordinate = ycoordinate;
		this.annotationInfo = annotationInfo;
	}

	@Id
	@SequenceGenerator(name="coordinate_sequence",sequenceName="coordinate_sequence", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="coordinate_sequence")
	@Column(name = "coordinateid", unique = true, nullable = false)
	public Long getCoordinateId() {
		return this.coordinateId;
	}

	public void setCoordinateId(Long coordinateid) {
		this.coordinateId = coordinateid;
	}

	@Column(name = "xcoordinate", precision = 17, scale = 17)
	public Double getxCoordinate() {
		return this.xCoordinate;
	}

	public void setxCoordinate(Double xcoordinate) {
		this.xCoordinate = xcoordinate;
	}

	@Column(name = "ycoordinate", precision = 17, scale = 17)
	public Double getyCoordinate() {
		return this.yCoordinate;
	}

	public void setyCoordinate(Double ycoordinate) {
		this.yCoordinate = ycoordinate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "startCoordinate")
	public Set<AnnotationInfo> getAnnotationInfo() {
		return this.annotationInfo;
	}

	public void setAnnotationInfo(
			Set<AnnotationInfo> annotationinfosForStartingcoordinateid) {
		this.annotationInfo = annotationinfosForStartingcoordinateid;
	}

}
