package edu.jhu.cvrg.dbapi.factory.hibernate;

// Generated Dec 7, 2013 2:31:41 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Uploadstatus generated by hbm2java
 */
@Entity
@Table(name = "uploadstatus", schema = "public")
public class UploadStatus implements java.io.Serializable {

	private long uploadStatusId;
	private DocumentRecord documentRecord;
	private String fileTransfer;
	private String fileConversion;
	private String recordCreation;
	private String annotationCreation;

	public UploadStatus() {
	}

	public UploadStatus(long uploadstatusid) {
		this.uploadStatusId = uploadstatusid;
	}

	public UploadStatus(long uploadstatusid, DocumentRecord documentrecord,
			String filetransfer, String fileconversion, String recordcreation,
			String annotationcreation) {
		this.uploadStatusId = uploadstatusid;
		this.documentRecord = documentrecord;
		this.fileTransfer = filetransfer;
		this.fileConversion = fileconversion;
		this.recordCreation = recordcreation;
		this.annotationCreation = annotationcreation;
	}

	@Id
	@Column(name = "uploadstatusid", unique = true, nullable = false)
	public long getUploadStatusId() {
		return this.uploadStatusId;
	}

	public void setUploadStatusId(long uploadstatusid) {
		this.uploadStatusId = uploadstatusid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "documentrecordid", insertable = false, updatable = false)
	public DocumentRecord getDocumentRecord() {
		return this.documentRecord;
	}

	public void setDocumentRecord(DocumentRecord documentrecord) {
		this.documentRecord = documentrecord;
	}

	@Column(name = "filetransfer", length = 75)
	public String getFileTransfer() {
		return this.fileTransfer;
	}

	public void setFileTransfer(String filetransfer) {
		this.fileTransfer = filetransfer;
	}

	@Column(name = "fileconversion", length = 75)
	public String getFileConversion() {
		return this.fileConversion;
	}

	public void setFileConversion(String fileconversion) {
		this.fileConversion = fileconversion;
	}

	@Column(name = "recordcreation", length = 75)
	public String getRecordCreation() {
		return this.recordCreation;
	}

	public void setRecordCreation(String recordcreation) {
		this.recordCreation = recordcreation;
	}

	@Column(name = "annotationcreation", length = 75)
	public String getAnnotationCreation() {
		return this.annotationCreation;
	}

	public void setAnnotationCreation(String annotationcreation) {
		this.annotationCreation = annotationcreation;
	}

}
